= Susi AI Skill Development


== What is Susi?

Susi is an open source intelligent personal assistant which has the capability to learn and respond better to queries. It is also capable of making to-do lists, setting alarms, providing weather and traffic info all in real time. Susi responds based on skills.

== What is a skill? How do we teach a skill?

A skill is a piece of code which performs a set of actions in order to respond to the user’s query. These skills are based on pattern matching which help them mapping the user’s query to a specific skill and responding accordingly. Teaching a skill to Susi is surprisingly very easy to implement. One can take a look at the Susi Skill Development Tutorial and a video workshop by Michael Christen.

I will try to give a basic idea on how to create a skill, it’s basic structure and some of the skills I developed in the first week.

=== Prepare to create a skill:

Head over to http://dream.susi.ai
Create a etherpad with some relevant name
Delete all text currently present in there
Start writing your skill
Adding to this, for testing a skill one can head over to Susi Web Chat Interface.

Basic Structure for calling an API:

    <Regular expression to be matched here>
    !console:<response given to the user>
    {
      "url":"<API endpoint>",
      "path":"<Json path here>"
    }
    eol
    
So, let me explain this line by line.

* The regular expression is the one to which the user’s query is matched first.
* The console is meant to output the actual response the user sees as response.
* In place of the “url”, the API endpoint is passed in.
“path” here specifies how we traverse through the response Json or Jsonp to get the object, starts with “$.”.
* At last, “eol” which is the end-of-line marks the end of a skill.


Let’s take an example for better understanding of this:

  random gif
  !console: $url$
  {
      "url" : "http://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC",
      "path" : "$.data[0].images.fixed_height"
  }
  eol 


*This skill responds with a link to a random gif.*

Steps involved:

* Match the string “random gif” with the user’s query.
* On successful match, make an API call to the API endpoint specified in “url”
* On response, extract the object at the specified path in the json under “path”
* Respond to the user with the “url” key’s value which would here be an URL of a GIF.

Let’s try it out on http://susi.ai/chat[Susi Web Chat]. For this, you will first have to load your skill using the dream command followed by etherpad name: 
    
    dream <etherpad name> 

And then you can start testing your skill.



So, we queried “random gif” and we got a response “Click Here!”. The complete URL didn’t show up because all the URLs are currently parsed and a hyperlink for each is created. So try clicking on it to find a GIF.



Now, let’s look at one more skill I developed during this period.


 #Returns the name of the president of a country
 president of *|who is the president of *| president *
 !console:$plaintext$
 {      "url":"https://api.wolframalpha.com/v2/query?input=president+$1$&output=JSON&appid=9WA6XR-26EWTGEVTE&includepodid=Result",
   "path" : "$.queryresult.pods[0].subpods[0]"
 }
 eol


Let’s understand this step by step:

* We have here *president of *|who is the president of *| president *, which means the user’s query matches with anyone of the following because of the use of pipe symbol “|”. The “**” here replaces a word or a list of words, which can be accessed like: “${index}$”  where index is replaced by the position of the “*” in the expression starting from 1.
* Now we have something new in the URL. See that  $1$  inside the URL? On runtime, that is replaced with the content of the “***” variable. So if a user puts in query like: “president of usa”, “usa” is mapped to $1$ and is replaced in the URL and appropriate API request is made.
* Then the path is traversed in the json response and the value of the “plaintext” key is used to respond to the user.


It’s now time to try it out on http://susi.ai/chat[Susi Web Chat].



So, we got our desired response here, i.e., the name of the president of usa.